name: uuite
version: 1.0.0+1
publish_to: none
description: Aplikasi pencarian aturan hukum UU ITE
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.1
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  very_good_analysis: 5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/docs/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/images/splashscreen.png"
  android_12:
    image: "assets/images/splashscreen.png"
